export const REMOVE_CLIENT = "REMOVE_CLIENT";
export const REMOVE_SUCCESS = "REMOVE_SUCCESS";

export const ADD_CLIENT ="ADD_CLIENT";
export const ADD_SUCCESS="ADD_SUCCESS";
export const ADD_FAIL="ADD_FAIL";

// Supplier

export const ADD_SUPPLIER ="ADD_SUPPLIER";
export const ADD_SUPPLIER_SUCCESS ="ADD_SUPPLIER_SUCCESS";
export const ADD_SUPPLIER_FAIL ="ADD_SUPPLIER_FAIL";
export const REMOVE_SUPPLIER ="REMOVE_SUPPLIER";
export const REMOVE_SUPPLIER_SUCCESS ="REMOVE_SUPPLIER_SUCCESS";

// Article 
export const ADD_ARTICLE ="ADD_ARTICLE";
export const ADD_ARTICLE_SUCCESS ="ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAIL ="ADD_ARTICLE_FAIL";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const REMOVE_ARTICLE_SUCCESS = "REMOVE_ARTICLE_SUCCESS";

// Product
export const ADD_PRODUCT ="ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS ="ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL ="ADD_PRODUCT_FAIL";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";


